### ISSUE TITLE
Not receiving faucet funds

### ISSUE THREAD

**Issue by mrosendin** [flare-eng/coston#6] opened 2021-02-09 19:51 UTC
I've waited over a day for the transaction to appear on [flarescan.org](flarescan.org) but the balance is empty, so I am unable to deploy contracts on the testnet.

```
macbook:coston matthew$ node faucet.js

Coston Testnet Faucet

XRPL Testnet connected.
Generate XRPL Testnet credentials at:
https://xrpl.org/xrp-testnet-faucet.html

XRPL Testnet Address: r4xAzAvXnJgz35Jvf9vcdvssJN8h5sTyNW
XRPL Testnet Secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Coston Network credentials:
Address: 0xb7b685dD1b52D2939bD6f5d9515635c5a633fFAA
Secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Saving credentials to file.

Sending 500 XRP to your Coston Network address.
Transaction submitted to the XRPL.
Transaction finalizing in the XRPL...
Transaction finalizing in the XRPL...

Success! View transaction here:
https://testnet.xrpl.org/transactions/03336F616F5583E7FCBE7A8799A7C189870B5D13E815C114CC23D5AB1AC2AA39

macbook:coston matthew$ cat costonAccount.json
{"address":"0xb7b685dD1b52D2939bD6f5d9515635c5a633fFAA","privateKey":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}

macbook:coston matthew$ cd metacoin-box
macbook:metacoin-box matthew$ truffle migrate --network coston --reset
Using network 'coston'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
insufficient funds for gas * price + value
```

**Comment by jmastr** [comment] 2021-02-12 13:34
Confirming. Happened to me too. 500 Test XRP were send, but address was not funded.

Address: 0xE07F37FAe8dc5e4CB74E6461E84886fE0503fB88

**Comment by sprwn** [comment] 2021-02-15 16:54
It looks like the issue is that the XRPL testnet via Ripple's server at [wss://s.altnet.rippletest.net:51233]() is missing history from that range of time. The error of the faucet is showing as: `"error: [MissingLedgerHistoryError(Server is missing ledger history in the specified range)]"`. We'll work to fix this ASAP, thank you for reporting it.

**Comment by xrpdevs** [comment] 2021-02-15 18:03
I noticed this issue a few days ago too, thought it was some error on my part.

I've been developing a wallet for the testnet, I'd be happy to send anyone a small amount of test-FXRP if it helps them to get started until this issue is resolved.

**Comment by sprwn** [comment] 2021-02-15 19:28
The issue is now fixed - here is a Coston transaction showing the working faucet from just now: https://flarescan.org/address/0xD5db841621c19Ef44c554679A1Bf78323CbA9711

**Closed by sprwn** 2021-02-15 19:28 UTC
